# Generated by Django 6.0.4 on 2026-06-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_color', models.CharField(max_length=100, verbose_name='Цвет машины')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка машины')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена машины')),
                ('car_date', models.DateField(blank=True, null=True, verbose_name='Дата выпуска машины')),
                ('colors', models.ManyToManyField(related_name='car', to='main.color', verbose_name='colors')),
            ],
        ),
    ]
