# Generated by Django 6.0.4 on 2026-06-02 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_owner_car_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main.owner', verbose_name='Имя владельцов'),
        ),
        migrations.AlterField(
            model_name='car',
            name='colors',
            field=models.ManyToManyField(related_name='cars', to='main.color', verbose_name='colors'),
        ),
    ]
