# Generated by Django 6.0.4 on 2026-06-02 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_car_owner_name_car_owner_alter_car_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuzov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuzov', models.CharField(max_length=100, verbose_name='Кузов машины')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='kuzov',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='main.kuzov', verbose_name='Кузов машины'),
        ),
    ]
