# Generated by Django 6.0.4 on 2026-06-02 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_kuzov_car_kuzov'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='kuzov',
            new_name='category',
        ),
    ]
