# Generated by Django 6.0.4 on 2026-06-02 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_kuzov_car_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kuzov',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='kuzov',
            new_name='name',
        ),
    ]
